//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int code_schedule { get; set; }
        public Nullable<int> hour_in_dey { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<int> groups { get; set; }
        public Nullable<int> subjectIn { get; set; }
        public Nullable<int> Teacher { get; set; }
        public Nullable<int> day { get; set; }
    
        public virtual @class class1 { get; set; }
        public virtual subjectToClass subjectToClass { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
