//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sqlEntities : DbContext
    {
        public sqlEntities()
            : base("name=sqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<statusN> statusN { get; set; }
        public virtual DbSet<techer> techer { get; set; }
        public virtual DbSet<Presence> Presence { get; set; }
        public virtual DbSet<subjectToClass> subjectToClass { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
    }
}
